* Rahil Sayyad
* Email Id: rahilsayyad389@gmail.com

In [42]:
# import labraries
import numpy as np
import pandas as pd
import seaborn as sns


## read data

In [43]:
df=sns.load_dataset("iris")

In [44]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

## Seprate dependant and independant variable

In [45]:
x=df.iloc[:,0:4]

In [46]:
y=df.iloc[:,4]

## split the data in train and test side

In [47]:
from sklearn.model_selection import train_test_split

In [48]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=11)

## import model


In [60]:
from sklearn.tree import DecisionTreeClassifier

In [87]:
cart=DecisionTreeClassifier

In [96]:
from sklearn.ensemble import BaggingClassifier
model = BaggingClassifier(n_estimators = 100, random_state=7)

## fit the model and predict the output

In [99]:
mx=model.fit(x_train,y_train)
mx

BaggingClassifier(n_estimators=100, random_state=7)

In [100]:
y_pred=mx.predict(x_test)

In [104]:
from sklearn.metrics import accuracy_score #accuracy_score
print(accuracy_score(y_test,y_pred))

0.9111111111111111


In [106]:
#creating confusion matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[14  0  0]
 [ 0 12  2]
 [ 0  2 15]]


In [105]:
from sklearn.metrics import classification_report # classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        14
  versicolor       0.86      0.86      0.86        14
   virginica       0.88      0.88      0.88        17

    accuracy                           0.91        45
   macro avg       0.91      0.91      0.91        45
weighted avg       0.91      0.91      0.91        45

